language: objective-c
osx_image: xcode8.3
xcode_project: RGViperChat.xcodeproj
xcode_scheme: RGViperChat
xcode_sdk: iphonesimulator10.3
before_install:
  - pod repo update
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace RGViperChat.xcworkspace -scheme RGViperChatTests CODE_SIGNING_REQUIRED=NO  